### ISSUE TITLE
Lien de téléchargement des données erroné ?

### ISSUE THREAD

**Issue by lorisamabile** [lovasoa/historique-velib-opendata#1]
Bonjour,
Le lien de téléchargement des données, dans le readme.md, renvoie une page d'erreur "Not Found" (https://github.com/lovasoa/historique-velib-opendata/releases/download/latest/stations.zip).
Je n'ai peut-être juste pas compris comment y accéder.
Merci pour ce jeu de données libre.

**Comment by ppeigne** [comment]
Le lien ne marche pas effectivement mais le dataset est accessible ici : https://github.com/lovasoa/historique-velib-opendata/releases. 

Merci pour ce dataset :)
